### ISSUE TITLE
Will not load at all

### ISSUE THREAD

**Issue by BurkenDev** [ikafly144/SlotMachine#10]
[11:39:26] [Server thread/INFO]: [SlotMachine] Loading server plugin SlotMachine v0.1.0
[11:39:55] [Server thread/INFO]: [SlotMachine] Enabling SlotMachine v0.1.0
[11:39:55] [Server thread/INFO]: [SlotMachine] Loading medal data...
[11:39:55] [Server thread/INFO]: [SlotMachine] Loading medal data... Done!
[11:39:55] [Server thread/INFO]: [SlotMachine] Medal data count: 0
[11:39:55] [Server thread/INFO]: [SlotMachine] enabled (version 0.1.0)
[11:39:55] [Server thread/ERROR]: Error occurred while enabling SlotMachine v0.1.0 (Is it up to date?)
        at SlotMachine.jar/net.sabafly.slotmachine.EventListener.<clinit>(EventListener.java:45) ~[SlotMachine.jar:?]
        at SlotMachine.jar/net.sabafly.slotmachine.SlotMachine.onEnable(SlotMachine.java:70) ~[SlotMachine.jar:?]
[11:39:55] [Server thread/INFO]: [SlotMachine] Disabling SlotMachine v0.1.0
[11:39:55] [Server thread/INFO]: [SlotMachine] Saving medal data...
[11:39:55] [Server thread/INFO]: [SlotMachine] Saving medal data... Done!
[11:39:55] [Server thread/INFO]: [SlotMachine] disabled (version 0.1.0)

**Comment by ikafly144** [comment]
Please update the plugin and let us know if the issue still occurs.
If it still occurs, please let us know what the error is.
